### PR TITLE
fixed the beutification problem

### PR DESCRIPTION
**Pull request by raji2004**

### CODE REVIEW

**Comment by raji2004** [comment]
please merge

**Comment by srivastavaritik** [comment]
> please merge

why did you removed the background image

**Comment by raji2004** [comment]
i asked for advice from others and they said it would look better without it

**Comment by raji2004** [comment]
> > please merge
> 
> why did you removed the background image

should i ad it back?

**Comment by srivastavaritik** [comment]
> > > please merge
> > 
> > 
> > why did you removed the background image
> 
> should i ad it back?

yes, please add it

**Comment by raji2004** [comment]
> > > > please merge
> > > 
> > > 
> > > why did you removed the background image
> > 
> > 
> > should i ad it back?
> 
> yes, please add it

Ok will do

**Pull request closed without merging**
