### PR TITLE
Enhanced the Login/Sign up page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Old Login/sign up pages
Screenshot 2023-05-23 at 4 11 12 PM

Screenshot 2023-05-23 at 4 11 20 PM

New Login/Sign up pages
Screenshot 2023-05-23 at 4 11 30 PM

Screenshot 2023-05-23 at 4 11 38 PM

The code had used pre-defined css classes being imported from other files, had to re-write a few of them to enhance the issue.
The issue took longer than i expected to reslove.
I think the new design additions included making the entire more prominent, the older design had a dull look and was not very engaging, in the new design , i tried enlarging the components with some additional hover-effects to make it more engaging.

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Clears issue #53

**Comment by srivastavaritik** [comment]
please resolve conflicts

**Comment by karthiknadar1204** [comment]
Will do @srivastavaritik by tomorrow
Thank you

**Comment by karthiknadar1204** [comment]
@srivastavaritik Could you please tell me how do i resolve these conflicts

**Comment by karthiknadar1204** [comment]
will submit pr again tomorrow

**Comment by karthiknadar1204** [comment]
@srivastavaritik Exams got over today, i have multiple issues, will clear them out tomorrow evening sure thing
Thank you for your patience

**Comment by srivastavaritik** [comment]
closing this as conflicts not resolved yet

**Pull request closed without merging**
