### PR TITLE
Built a modal for displaying the contributors

### PR DESCRIPTION
**Pull request by nirajacharyaa**
The word contributors may be better instead of developers. Got the contributor's list from GitHub API.
Please review and let me know if any changes are required.
image

### CODE REVIEW

**Comment by srivastavaritik** [comment]
> The word contributors may be better instead of developers. Got the contributor's list from GitHub API. Please review and let me know if any changes are required. image

hey @nirajacharyaa , everything looks good and I think `Contributors` will be better than Developers.But one thing that, can you make this modal background in some dark color?

**Comment by nirajacharyaa** [comment]
Sure, will do that.

**Comment by nirajacharyaa** [comment]
Is this ok?
image

**Comment by srivastavaritik** [comment]
> Is this ok? image

Yes, it's looking good now.

**Review by srivastavaritik — APPROVED** [review]

**Comment by srivastavaritik** [comment]
Good work @nirajacharyaa ⚡.
Thanks for contributing.

**Comment by nirajacharyaa** [comment]
Welcome, my pleasure.

**Pull request merged**
