### PR TITLE
Recreated forgot password page

### PR DESCRIPTION
**Pull request by hs-07**
Changes done in forgot password page can be seen in attached screenshot below:

image

### CODE REVIEW

**Comment by hs-07** [comment]
@srivastavaritik 
Why it is not merging ?
and also why my PR failed all the checks?

**Comment by srivastavaritik** [comment]
> @srivastavaritik Why it is not merging ? and also why my PR failed all the checks?

image
this is the issue, please resolve this and please add the navbar and footer on the page

**Comment by hs-07** [comment]
@srivastavaritik okay got it... I will try fixing this issue

**Comment by hs-07** [comment]
@srivastavaritik 
But in my localhost it is working properly, no error is showing.

**Comment by hs-07** [comment]
@srivastavaritik i got it .... i found what was the problem
I will make a new PR in which footer and navbar will be included in forgotpassword page

**Comment by srivastavaritik** [comment]
okay, I am merging this pull request

**Pull request merged**
